# clipboard api is still unstable, so web-sys requires the below flag to be passed for copy (ctrl + c) to work
# https://rustwasm.github.io/docs/wasm-bindgen/web-sys/unstable-apis.html
# check status at https://developer.mozilla.org/en-US/docs/Web/API/Clipboard#browser_compatibility
[build]
rustflags = [
    "--cfg=web_sys_unstable_apis",
    "-Z", "threads=8"
]
#target = "wasm32-unknown-unknown"

# [target.x86_64-unknown-linux-gnu]
# linker = "rust-lld"
# # linker = "mold"
# # linker = "lld"
# rustflags = ["-C", "linker-flavor=ld.lld"]

[target.'cfg(all(target_arch = "x86_64", target_os = "linux"))']
linker = "clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=mold",
    # "-C", "target-feature=-crt-static"
]
